spring.application.name=teacherexchange

#config database
##
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/teacher_exchange
spring.datasource.username=root
spring.datasource.password=Khoango35thd@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
##

server.port=9090

#config upload file
###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB  

# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
###

